stages:
  - Build

Build minicrawler container:
  tags: [ minicrawler ]
  stage: Build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker Buildx create --use --driver docker-container --name Builder-$CI_JOB_ID
    - docker Buildx inspect --bootstrap
  script:
    - docker Buildx bake --file docker-bake.hcl minicrawler --push
  after_script:
    - docker Buildx rm Builder-$CI_JOB_ID
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH