stages:
  - Docker

Build minicrawler container:
  tags: [ shell ]
  stage: Docker
  before_script:
    - docker buildx rm --all-inactive --force
    - docker buildx ls | grep multi-builder || docker buildx create --use --bootstrap --name multi-builder
  script:
    - docker buildx bake --file docker-bake.hcl minicrawler --print
    - docker buildx bake --file docker-bake.hcl minicrawler --push
  after_script:
    - docker buildx prune --all --keep-storage=10GB --force
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always