stages:
  - Docker

Build minicrawler container:
  tags: [ shell ]
  stage: Docker
  before_script: >
    if ! docker context inspect builder > /dev/null 2>&1; then
      docker context create builder
    fi
    
    if ! docker buildx inspect builder > /dev/null 2>&1; then
      docker buildx create --name builder --use
    fi

  script:
    - docker buildx bake --file docker-bake.hcl minicrawler --print
    - docker buildx bake --file docker-bake.hcl minicrawler --push

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

Cleanup docker cache:
  tags: [ shell ]
  stage: Docker
  script:
    - docker buildx prune --force
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true