name: Build and Test Minicrawler

on:
  - workflow_dispatch
  - pull_request
  - push

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - uses: ./.github/actions/build
      - name: make check
        run: make check

  try:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - uses: ./.github/actions/build
      - name: try run minicrawler
        run: ./minicrawler5 https://www.testomato.com/humans.txt